/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MissingDrugsRouteImport } from './routes/missing-drugs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinDoctorRouteImport } from './routes/join-doctor'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacyRegisterRouteImport } from './routes/pharmacy.register'
import { Route as PharmacyDashboardRouteImport } from './routes/pharmacy.dashboard'
import { Route as FeedNewRouteImport } from './routes/feed.new'
import { Route as DoctorVerificationRouteImport } from './routes/doctor.verification'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as ConsultationIdRouteImport } from './routes/consultation.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as FeedPostIdRouteImport } from './routes/feed.post.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingDrugsRoute = MissingDrugsRouteImport.update({
  id: '/missing-drugs',
  path: '/missing-drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinDoctorRoute = JoinDoctorRouteImport.update({
  id: '/join-doctor',
  path: '/join-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRegisterRoute = PharmacyRegisterRouteImport.update({
  id: '/pharmacy/register',
  path: '/pharmacy/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyDashboardRoute = PharmacyDashboardRouteImport.update({
  id: '/pharmacy/dashboard',
  path: '/pharmacy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedNewRoute = FeedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FeedRoute,
} as any)
const DoctorVerificationRoute = DoctorVerificationRouteImport.update({
  id: '/doctor/verification',
  path: '/doctor/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationIdRoute = ConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPostIdRoute = FeedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => FeedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/feed': typeof FeedRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/join-doctor': typeof JoinDoctorRoute
  '/login': typeof LoginRoute
  '/missing-drugs': typeof MissingDrugsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/doctor/verification': typeof DoctorVerificationRoute
  '/feed/new': typeof FeedNewRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/pharmacy/register': typeof PharmacyRegisterRoute
  '/feed/post/$id': typeof FeedPostIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/feed': typeof FeedRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/join-doctor': typeof JoinDoctorRoute
  '/login': typeof LoginRoute
  '/missing-drugs': typeof MissingDrugsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/doctor/verification': typeof DoctorVerificationRoute
  '/feed/new': typeof FeedNewRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/pharmacy/register': typeof PharmacyRegisterRoute
  '/feed/post/$id': typeof FeedPostIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/feed': typeof FeedRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/join-doctor': typeof JoinDoctorRoute
  '/login': typeof LoginRoute
  '/missing-drugs': typeof MissingDrugsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/doctor/verification': typeof DoctorVerificationRoute
  '/feed/new': typeof FeedNewRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/pharmacy/register': typeof PharmacyRegisterRoute
  '/feed/post/$id': typeof FeedPostIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/feed'
    | '/how-it-works'
    | '/join-doctor'
    | '/login'
    | '/missing-drugs'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/admin/verifications'
    | '/checkout/return'
    | '/consultation/$id'
    | '/doctor/$id'
    | '/doctor/verification'
    | '/feed/new'
    | '/pharmacy/dashboard'
    | '/pharmacy/register'
    | '/feed/post/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/feed'
    | '/how-it-works'
    | '/join-doctor'
    | '/login'
    | '/missing-drugs'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/admin/verifications'
    | '/checkout/return'
    | '/consultation/$id'
    | '/doctor/$id'
    | '/doctor/verification'
    | '/feed/new'
    | '/pharmacy/dashboard'
    | '/pharmacy/register'
    | '/feed/post/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/feed'
    | '/how-it-works'
    | '/join-doctor'
    | '/login'
    | '/missing-drugs'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/admin/verifications'
    | '/checkout/return'
    | '/consultation/$id'
    | '/doctor/$id'
    | '/doctor/verification'
    | '/feed/new'
    | '/pharmacy/dashboard'
    | '/pharmacy/register'
    | '/feed/post/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DoctorsRoute: typeof DoctorsRoute
  FeedRoute: typeof FeedRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  JoinDoctorRoute: typeof JoinDoctorRoute
  LoginRoute: typeof LoginRoute
  MissingDrugsRoute: typeof MissingDrugsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ConsultationIdRoute: typeof ConsultationIdRoute
  DoctorIdRoute: typeof DoctorIdRoute
  DoctorVerificationRoute: typeof DoctorVerificationRoute
  PharmacyDashboardRoute: typeof PharmacyDashboardRoute
  PharmacyRegisterRoute: typeof PharmacyRegisterRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-drugs': {
      id: '/missing-drugs'
      path: '/missing-drugs'
      fullPath: '/missing-drugs'
      preLoaderRoute: typeof MissingDrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-doctor': {
      id: '/join-doctor'
      path: '/join-doctor'
      fullPath: '/join-doctor'
      preLoaderRoute: typeof JoinDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/register': {
      id: '/pharmacy/register'
      path: '/pharmacy/register'
      fullPath: '/pharmacy/register'
      preLoaderRoute: typeof PharmacyRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/dashboard': {
      id: '/pharmacy/dashboard'
      path: '/pharmacy/dashboard'
      fullPath: '/pharmacy/dashboard'
      preLoaderRoute: typeof PharmacyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/new': {
      id: '/feed/new'
      path: '/new'
      fullPath: '/feed/new'
      preLoaderRoute: typeof FeedNewRouteImport
      parentRoute: typeof FeedRoute
    }
    '/doctor/verification': {
      id: '/doctor/verification'
      path: '/doctor/verification'
      fullPath: '/doctor/verification'
      preLoaderRoute: typeof DoctorVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/$id': {
      id: '/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof ConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/post/$id': {
      id: '/feed/post/$id'
      path: '/post/$id'
      fullPath: '/feed/post/$id'
      preLoaderRoute: typeof FeedPostIdRouteImport
      parentRoute: typeof FeedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FeedRouteChildren {
  FeedNewRoute: typeof FeedNewRoute
  FeedPostIdRoute: typeof FeedPostIdRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedNewRoute: FeedNewRoute,
  FeedPostIdRoute: FeedPostIdRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DoctorsRoute: DoctorsRoute,
  FeedRoute: FeedRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  JoinDoctorRoute: JoinDoctorRoute,
  LoginRoute: LoginRoute,
  MissingDrugsRoute: MissingDrugsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ConsultationIdRoute: ConsultationIdRoute,
  DoctorIdRoute: DoctorIdRoute,
  DoctorVerificationRoute: DoctorVerificationRoute,
  PharmacyDashboardRoute: PharmacyDashboardRoute,
  PharmacyRegisterRoute: PharmacyRegisterRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
